### ISSUE TITLE
Error with repair menu

### ISSUE THREAD

**Issue by Gonimy-Vetrom** [Bobster82/FS22_VehicleInfo#1]
When opening the repair menu, I got this error:
FS22_VehicleInfo/VIData.lua:93: attempt to index field 'vi' (a nil value)
2021-12-12 17:50 Error: Running LUA method 'update'.

This first time launched this mod. I have not saved the game.

**Comment by Bobster82** [comment]
Hey,

I was trying to reproduce it, but if i go to the repair menu and repair, i don't get a error. (I drove to the shop to repair the vehicle)
Can u explain your steps a bit more?
Does this happen everytime or only on not saved games?

**Comment by Gonimy-Vetrom** [comment]
Later I tried to do it on the saved game. Also got the same error.
The error appears at the stage when I want to change the configuration.

**Comment by Bobster82** [comment]
Ah ok, thanks... Im going to look into it

**Comment by Bobster82** [comment]
Can you try it with the new version 1.0.0.1 ?

**Comment by Gonimy-Vetrom** [comment]
Thank you. There are no problems anymore!

**Comment by Bobster82** [comment]
Great, I must have removed those nil checks when i cleaned up my code haha.
Thanks for testing!
