### ISSUE TITLE
Problem with VInfo_config.xml

### ISSUE THREAD

**Issue by SavageMkII** [Bobster82/FS22_VehicleInfo#11]
Hello, and thank you for this great mod!

I'm having a problem with the V1.0.0.4. It seems to not be saving the VInfo_config.xml file properly. This is what it looks like.

https://gist.github.com/SavageMkII/aaf54c09571bd49458aa4f766d98cc43

I have tested again with V1.0.0.3 and it works as it should. I also tried again with V1.0.0.4 and a fresh savegame with no other mods and it doesn't save the file properly.

**Comment by Bobster82** [comment]
Thats strange, I didnt change anything in the save environment. I need to look into that.
Thanks

**Comment by Bobster82** [comment]
Try again with the new 1.0.0.5
https://github.com/Bobster82/FS22_VehicleInfo/raw/master/Release/FS22_VehicleInfo.zip

**Comment by SavageMkII** [comment]
Yes, it is working properly again. Thanks!
