### ISSUE TITLE
move VI if you expand the Help menue

### ISSUE THREAD

**Issue by RealNeo80** [Bobster82/FS22_VehicleInfo#12]
have you thought about moving VI downwards if you expand the help menu via F1?

**Comment by Bobster82** [comment]
In my personal experience, I don't like it. How often do you use the help menu? For me its hardly a few min per game session. Its also very busy onscreen if you have the help menu on and the vehicle overview.
But it can be done, thats not the issue ;) I still need to update the current version to move the text and other stuff I added ;)

**Comment by RealNeo80** [comment]
hmm thats one sight, for me i have mostly the help menue open (just be lazy to close it :p) I used VehicleInspector before, but i found VI and was very happy about the Click and switch funktion of it, so i think it will be the Info in Charge for the time beeing.

on the other hand i´m searching for informations about the active missions, do see it directly on the main screen. I do much of the missions, but if i have actived all 3 of them sometimes i forget what to do and have to look all the time inside the menue, 
so if the Info will Tell me the most necessary infos about the mission Like Field / Job / Fruit / Sellpoint
i would be really happy ;)

**Comment by Bobster82** [comment]
>  i found VI and was very happy about the Click and switch funktion of it, so i think it will be the Info in Charge for the time beeing.

Youre not using the reorder function? I like that one too :P 

> on the other hand i´m searching for informations about the active missions, do see it directly on the main screen. I do much of the missions, but if i have actived all 3 of them sometimes i forget what to do and have to look all the time inside the menue, so if the Info will Tell me the most necessary infos about the mission Like Field / Job / Fruit / Sellpoint i would be really happy ;)

I like a challenge (Im not a programmer and learning LUA trough FS ;) ) and we can work things out. So point out the things you would like this mod could do (or changes u like to see) and I try to implement those. 


Its hard to show a lot of info and still keep it tidy and easy to read ;)
Some features:
Show mod under help menu
Drag mod where u want it to display it
Show if leased/mission vehicles on/off (with * for leased and ** for mission vehicles)
Show on which field on/off

**Comment by RealNeo80** [comment]
i think i know lua less then you, but as you say its a challenge ;) have you commited all changes you made? then i will make me a fork and have a look. what do you mean with recording function? 
about leased and field working on, it was already implemented in the vehicle inspector, i will have a look here 

by the way do you have discord?

**Comment by Bobster82** [comment]
I have a bunch of not ordered code that needed to be implemented ;)

not recording, but re-order ;) as in sorting

I do have some code lying around with field info and if leased or not, have a beta running on my pc, still need to commit some of these to the main (also learning git ;) )

I dont have discord, can download it if needed. But I dont have a setup with mic

**Comment by RealNeo80** [comment]
i also mostly write in dc, but if you have not setup an server it won´t help ;)
btw whats your main language?

**Comment by Bobster82** [comment]
> btw whats your main language?

Its Dutch ;)

**Comment by RealNeo80** [comment]
ok, so i think the english is best base for us ;) i speak german. On the other hand i come from object pascal, so i know about programming, but the lua  language is nearly complete new for me :p

**Comment by Bobster82** [comment]
English it is ;)
I never coded much, I read some stuff from the internet en try bunch of things till it works or till im tired of it ;)

I setup a discord, maybe helpfull:
https://discord.gg/852TJx2Bqc

**Comment by RealNeo80** [comment]
sent you a bug by discord
