### ISSUE TITLE
conflict with mod from FS ModHub

### ISSUE THREAD

**Issue by meda22** [Bobster82/FS22_VehicleInfo#13]
First - thanks for a great mod!
I just want to let you know that there is a naming conflict with mod in FS modhub (https://www.farming-simulator.com/mod.php?lang=en&country=us&mod_id=228319&title=fs2022) - which is completely different mod... but it can cause issues when player is updating mods in-game. I suppose you can do little about it... but just a little heads-up.

**Comment by SavageMkII** [comment]
I was thinking of opening an issue about this too. Can we rename your mod in our mod folder, or would that cause problems with the mod itself?

**Comment by Dzi4d3k** [comment]
Unfortunately it seems that the one who first officially (at Giants) reserve mod name is better position to keep chosen mod name.
Actually kenny456 had it also for FS19:
https://www.farming-simulator.com/mod.php?lang=en&country=us&mod_id=154541

**Comment by Bobster82** [comment]
Hi all,

Im sorry this has happend. I submitted my mods to the modhub, but giants was just a pain in the ass with all the little adjustments, so I stopped trying to get it on modhub. (and stopped working on this mod, as the fun was out of it)
I did already had this mod for fs19, but not for public. So who's first on modhub has the advantage.

You can rename the mod file, but it wont change the name in the game. It also resets the order of the vehicles.

I dont know if i want to change the name, my fun of making mods for fs is gone. The mod is still working, only it has a conflict with the same named mod

If someone else wants to make a pull request for changes, be my guest ;)

Im very sorry for my lack of support atm.

**Comment by meda22** [comment]
@Bobster82 
I definitely didn't mean that comment any bad way ;) but really just as heads up. 
It is quite a pity that Giants can weary good modders from another work. The mod works superb - so thanks for that! The naming conflict just means to be bit more careful when updating mods from modhub :)

**Comment by Bobster82** [comment]
@meda22 , Thanks for the positive feedback, Means a lot!

p.s. I also really dont know how to call my mod ;)

**Comment by meda22** [comment]
Well, finding the a proper name is always the hardest thing in the programming :D Something like "Vehicle Tab Info" or "Vehicle Tab Manager"... as there is quite some functionality regarding vehicle "tabbing" in your mod :)

**Comment by Sie-vo** [comment]
I've renamed the mod zip file and in moddesc.xml the title. That works !
