### ISSUE TITLE
Main guage disappeared due new patch

### ISSUE THREAD

**Issue by s4dnz** [Bobster82/FS22_VehicleInfo#15]
I was jump in MP and the gauge went disappear so I cant tell how I fast I go or knowing I did attachment the trailer or tools properly.

So I told owner of MP server I will have look at SP to find out issues. Far I can tell from dev command throw errors most vehicle;
**_"Error: Running LUA method 'draw'." from vehicleinfo.lua:618 bad arguement hashtag2._**

I thought that was issues so I go back main menu and turn off Vehicle Info mod and rejoin the game, the gauge was back and working.

The error was there before new Patch but, due Patch has been installed and it's managed broke main gauge.

**Comment by Bobster82** [comment]
Hello s4dnz,

I think u using a different mod with the same name. I dont have a file with vehicleinfo.lua ;)
Can u give a screenshot of the mod when its working?
