### ISSUE TITLE
Tabbing is blocked

### ISSUE THREAD

**Issue by RealNeo80** [Bobster82/FS22_VehicleInfo#16]
still active on this project? After long time i had time again to play FS and found out the VI is blocking the tabbing between the tractors.

**Comment by Bobster82** [comment]
No, I'm sorry. I haven't played or mod the game for a long time. I guess the new update/patch broke something?
I can't work on it

**Comment by Bobster82** [comment]
@RealNeo80 , I didn't had any problems with tabbing when I played yesterday. I have game version 1.6. Maybe a mod conflict?

**Comment by Bobster82** [comment]
No further reactions
