### ISSUE TITLE
Tabbing not possible due to inconsistent vehicle order

### ISSUE THREAD

**Issue by santaranger** [Bobster82/FS22_VehicleInfo#3]
This is similar issue to sperrgebiet's VehicleExplorer, see https://github.com/sperrgebiet/FS22_VehicleExplorer/issues/9

There are some circumstances that cause vehicle ids to become permanently inconsistent, which breaks functionality in multiple ways of course. I had had for example in my verhicle.xml id values of 1,2,3,4,5,8,8. This caused tabbing to block at id=5. I was also unable to select one of the 8's by clicking on the list entry.

As in VEx, I suspect here as well that some vehicle removal event is not handled correctly (I do a lot of missions with borrowed equipment). Another cause might be problems when re-ordering the list, but I was not able to reproduce it 100%.

Some steps to reproduce a peculiar behavior:
1. start new game
2. buy 4 tractors
3. sell the second tractor in the list (leaving you with 3 tractors)
4. enter the last tractor
5. try to swap (reorder) the last tractor with first tractor
result:
![image](https://user-images.githubusercontent.com/7590290/148044547-1b66d0fc-75d4-4716-8aca-d2418141aba9.png)

**Comment by Bobster82** [comment]
Hey, Thanks for pointing out this problem. I will check this when im back from my vacation and have the time. I will check it for sure ;)

**Comment by Bobster82** [comment]
Ow, checked it and it was something simple btw, had to check it ;) I think its fixed with the 1.0.0.3. Didn't test it long.
Let me know if all is ok.

Thanks

**Comment by santaranger** [comment]
Looks good now, thanks for the quick fix.
