### ISSUE TITLE
log : Invalid mod name

### ISSUE THREAD

**Issue by yann-mrt** [Bobster82/FS22_VehicleInfo#5]
Good day, 
I have this error in my log when starting with V1.0.0.3
Error: Invalid mod name 'FS22_VehicleInfo-master'! Characters allowed: (_, A-Z, a-z, 0-9). The first character must not be a digit.
Any idea?
Thanks for your time
Yann

**Comment by yann-mrt** [comment]
Forget about it, I find MY mistake (I was keeping the dl name from Github). I remove "-master" from the name... et Voila !!!

**Comment by Bobster82** [comment]
Haha, was just about to comment... I have also a release map in it with the file already zipped ;)
