### ISSUE TITLE
Setting screen version doesn't match

### ISSUE THREAD

**Issue by yann-mrt** [Bobster82/FS22_VehicleInfo#6]
Good day,
When I open the setting screen the version # appear (1.0.0.2) doesn't match with the version I use (1.0.0.3)
![image](https://user-images.githubusercontent.com/74056604/148404435-eb2fdf90-6c56-41f1-a5e6-ec63ffce2229.png)

**Comment by Bobster82** [comment]
Ah, I didnt update that number in the scripts... in my other mod it it linked... I will fix that later, but no worries, its the 1.0.0.3 ;)

Thanks for pointing it out

**Comment by Bobster82** [comment]
btw, do you like the settings menu? or do you want to see a fs22 style menu?

**Comment by yann-mrt** [comment]
Not sure, how will be your fs22 style ?

**Comment by Bobster82** [comment]
The same I have in my other mod, autorepair ;)

**Comment by yann-mrt** [comment]
Sorry i don't use this one, since it is "included" in AD. Any pics ?

**Comment by Bobster82** [comment]
Ah ok, Its not only auto repair, it also does paint and cleaning ;)

<img width="1463" alt="image" src="https://user-images.githubusercontent.com/47780758/148406994-47e85ad8-4c34-4239-a045-2ef6e8cd0e25.png">

**Comment by yann-mrt** [comment]
OK look interesting. 
I think I would prefer the fs22 style, look more "integrated" into the game.

**Comment by Bobster82** [comment]
Ok, thanks for the comment. Will see when I do something with it. I also want to add translations and some other small features/changes.

**Comment by yann-mrt** [comment]
I never did translation, and never did anything with GitHub except downloading files. but I could give a try to translate in French if you are interested.

**Comment by Bobster82** [comment]
yeah, french would be nice... doing it the github way is a bit tougher, but you can always drop the translated file here, so i can attach it... but i need to write the language file 1st ;)

**Comment by yann-mrt** [comment]
Ok when you done the file in your side, give me signal.

**Comment by Bobster82** [comment]
fixed with the 1.0.0.4
