### ISSUE TITLE
Move the text

### ISSUE THREAD

**Issue by yann-mrt** [Bobster82/FS22_VehicleInfo#7]
Good day,
Any way to be able to move the text. For me it will be a bit down but other player could want it in other position
![image](https://user-images.githubusercontent.com/74056604/148418489-885920e7-14cc-48ed-8a13-cd7c04ec64c6.png)

**Comment by Bobster82** [comment]
Yeah, it isnt that hard to adjust the text... maybe I will add a function to drag the text around... but for now, you can edit the vinfo.lua file and change, line54: VInfo.text.posY = 0.95;  1 is top and 0 is bottom, so change it between that ;)

**Comment by yann-mrt** [comment]
Great, 0.93 fit perfectly to me. ;o)
But for sure a drag function would be the best.

**Comment by Bobster82** [comment]
Its added in the 1.0.0.6 version
