### ISSUE TITLE
Not kepping Keyboard control

### ISSUE THREAD

**Issue by yann-mrt** [Bobster82/FS22_VehicleInfo#9]
Good day,

When I change the keyboard control (remove the RMB because it is in conflict with AD) the key control come back when restarting

Yann

**Comment by Bobster82** [comment]
I dont understand exactly what you mean. Is my mod blocking key controls? Or only the spacebar issue? And the conflict with ad? Mouse not working or ad not working?  ... Will test some stuff tomorrow. Can u also post a log.txt file? Maybe i can find something usefull in it...
Thanks for testing and letting me know all these things.

**Comment by yann-mrt** [comment]
_Is my mod blocking key controls?_  -> I don't think, but when I try to remove the RMB from your key control, it is come back when I restart the game.
_only the spacebar issue?_ -> not only space bar but as well the RMB with AD
_And the conflict with ad?_  ->Yes, RMB with AD is to move a node when you are in edit mode.
_Mouse not working or ad not working?_  -> AD RMB in edit mode not working


[log.txt](https://github.com/Bobster82/FS22_VehicleInfo/files/7825056/log.txt)

**Comment by Bobster82** [comment]
I think I have found this issue and its just a keymapping issue.
AD uses middle mouse to activate mouse cursor and right mouse for stuff in edit mode. I use right mouse button to activate the mouse cursor.
You can either change AD mouse from middle to right mouse button and use the middle to drag around points and other stuff in edit mode, or change VInfo mouse to middle mouse button.

When editing the key controls, be sure to save the controls before leaving the menu ;)

**Comment by yann-mrt** [comment]
Great, it is working now and keyboard setting is kept (I didn't save). I prefer to keep the AD keyboard setup as I'm use to those from long time.
other think I find:
When I setup "Show vehicle not active" to No, and then restart the game the setup come back to the original. I had to make this setup on every restart. Any way to keep the last setup?

**Comment by Bobster82** [comment]
Nice to hear its working as it should ;)

I just got a issue with the same probleme, i need to look into it.
See:  https://github.com/Bobster82/FS22_VehicleInfo/issues/11

**Comment by yann-mrt** [comment]
Oops didn't see someone was already reporting.

**Comment by Bobster82** [comment]
No problem. Will close this one
